trigger:
  branches:
    exclude: 
    - u/*
pr:
  branches:
    include:
    - main
variables:
- name: TeamName
  value: machinelearning-tools
- name: BuildArgs
  value: /p:DotNetSignType=$(SigningType)
- if eq(variables['Build.DefinitionName'], 'dotnet.AzCopyNet')
  - name: OfficialBuildArgs
    value: /p:DotNetSignType=$(SigningType)
           /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
           /p:PublishToSymbolServer=true
           /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
           /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)

  
jobs:
- job: Build
  strategy:
    matrix:
      Win-x64-Release:
        _configuration: Release
        _Use32Bit: false
        _platform: x64
  pool:
    name: VSEng-MicroBuildVS2019
  steps:
    - task: MicroBuildSigningPlugin@3
      displayName: Install signing plugin
      inputs:
        signType: $(SigningType)
        feedSource: 'https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json'
      condition: and(succeeded(), eq(variables['SigningType'], 'real'), eq(variables['_platform'], 'x64'))
      
    - script: eng\common\CIBuild.cmd 
                -configuration $(_configuration)
                -prepareMachine
                -warnAsError 0
                -bl 
                /p:Use32Bit=$(_Use32Bit)
                /p:Test=False
                /p:Pack=False
                /p:Publish=False
                /p:Sign=False
                $(BuildArgs)
      displayName: Build
      condition: succeeded()

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        publishTestResults: true
        arguments: '--collect "Code coverage"
                    --no-build
                    -c $(_configuration)
                    --settings "CodeCoverage.runsettings"'
        projects: '**/*.Test.csproj'
      condition: succeeded()
      env:
        GRANTSETFIXSASTOKEN2: $(GRANTSETFIXSASTOKEN2)
    
    - script: eng\common\CIBuild.cmd 
                -configuration $(_configuration)
                -prepareMachine
                -warnAsError 0
                -bl 
                /p:Use32Bit=$(_Use32Bit)
                /p:Build=False
                /p:Restore=False
                /p:Test=False
                /p:Pack=True
                /p:Sign=True
                /p:DotNetFinalVersionKind=release
                /p:Publish=False
                $(BuildArgs)
      displayName: Pack
      condition: succeeded()

    # Should always run
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(_configuration)'
        ArtifactName: '$(_platform) $(_configuration) log folder'
        publishLocation: Container
      condition: true
      continueOnError: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/artifacts/Packages/$(_configuration)/'
        ArtifactName: '$(_platform) $(_configuration) packages folder'
        publishLocation: Container
      displayName: Publish packages folder
      continueOnError: true
      condition: eq(variables['_configuration'], 'Release')
